### ISSUE TITLE
UI thread SynchronizationContext

### ISSUE THREAD

**Issue by freever** [wintoncode/Winton.Extensions.Threading.Actor#33]
Hi folks

I was looking for a lightweight c# implementation of an actor system to use in a Xamarin app when I came across this little gem of a library 👍 

I have one question though. I'm not very knowledgable about the intricacies of task scheduling, but I have been bitten many times before by the exceptions thrown when background work arrives back on the UI without being properly marshalled back to the UI thread, so I was wondering if anyone has some pointers as to how to go about this. 

Let's say I have a ViewModel which is running in the UI thread. I spin up an actor, invoke some async functionality on the actor which returns something back to my ViewModel as the result of the Task. If I push the result out to my UI, will I get a threading exception because the work was done in a different SynchronizationContext, or will the actor magic bring it back onto the calling context automatically? 

Thanks

**Comment by freever** [comment]
UPDATE: Ok, it does throw an exception. 

I can get hold of the main thread SynchronizationContext using [Xamarin.Essentials](https://docs.microsoft.com/en-us/xamarin/essentials/main-thread) but I would need a way to supply that context to the ActorTaskScheduler, and I can't see a neat way to do that (if indeed it is at all feasible).

**Comment by jhickson** [comment]
Hi @freever,

It won't return you to the calling context unfortunately as part of getting the actor to work requires forgetting the context. I'm not familiar with Xamarin, but in WPF you'd need to use the Dispatcher to get things back onto the UI thread.

NB: though I'm the original author of this library, I no longer work for Winton so whilst it might be feasible to get the actor to return you to the UI context, I'm completely unable to say whether anybody would be able to do the work.

**Comment by freever** [comment]
@jhickson Thanks, I am doing as you suggest and using Xamarin's methods to marshall back to the UI thread.
